# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9c029f15b454b1d48e88ec924d018c3e"
name = "first-ever-app"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobject_definitions,read_metaobjects,read_products,write_metaobject_definitions,write_metaobjects,write_orders,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[metaobjects]
standard_metaobjects = [ "shopify--qa-pair" ]

[product.metafields.app.faqs]
name = "Product FAQs"
description = "List of FAQ entries associated with this product"
type = "list.metaobject_reference<shopify--qa-pair>"

  [product.metafields.app.faqs.access]
  admin = "merchant_read_write"
  storefront = "public_read"

[order.metafields.app.date_of_birth]
name = "Date of Birth"
description = "Date of birth associated with the order"
type = "date"

  [order.metafields.app.date_of_birth.access]
  admin = "merchant_read_write"

[order.metafields.app.verified_at]
name = "Verified At"
description = "Timestamp when the order was verified"
type = "date"

  [order.metafields.app.verified_at.access]
  admin = "merchant_read_write"
